### ISSUE TITLE
_FPHSA_FAILURE_MESSAGE

### ISSUE THREAD

**Issue by darkoverlordofdata** [preshing/CMakeDemo#1]
I'm trying this on Win10 with msys2 installed, and it fails unable to find SDL2; SDL2 is installed right next to it:
C:\Users\darko\Documents\GitHub\CMakeDemo
C:\Users\darko\Documents\GitHub\extern\SDL2-2.0.5

> cmake -G "Visual Studio 15 2017 Win64" ..
-- The C compiler identification is MSVC 19.11.25547.0
-- The CXX compiler identification is MSVC 19.11.25547.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Generating header file: C:/Users/darko/Documents/GitHub/CMakeDemo/build/demo-config.h
CMake Error at C:/msys64/mingw64/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL2 (missing: SDL2_INCLUDE_DIRS SDL2_LIBS SDL2_DLLS)
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  modules/FindSDL2.cmake:57 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)

**Comment by darkoverlordofdata** [comment]
Nevermind. The extern folder belongs inside the project folder. Now it works!

**Comment by allen-ash** [comment]
@darkoverlordofdata ，I am facing the same problem.  I put the extern folder inside the project folder, but it still not work. Please tell me how to do it if you remember.
`Generating header file: C:/Users/allen/Desktop/courses/DL/CMakeDemo/build/demo-config.h
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find SDL2 (missing: SDL2_INCLUDE_DIRS SDL2_LIBS SDL2_DLLS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  modules/FindSDL2.cmake:57 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)`

**Comment by allen-ash** [comment]
@darkoverlordofdata now I know, It's because the different version between what I have downloaded and specified in FindSDL2.cmake with SDL. Sorry to bother.
